/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    InputField: typeof import('./src/components/form/InputField.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LoginPopover: typeof import('./src/components/layout/LoginPopover.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
  }
}
