/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGarment: typeof import('./src/components/clothing/AddGarment.vue')['default']
    AddGarmentForm: typeof import('./src/components/clothing/AddGarmentForm.vue')['default']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next/components/BForm')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    CheckboxField: typeof import('./src/components/form/CheckboxField.vue')['default']
    ClothingSelector: typeof import('./src/components/clothing/ClothingSelector.vue')['default']
    DropdownField: typeof import('./src/components/form/DropdownField.vue')['default']
    InputField: typeof import('./src/components/form/InputField.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    LoginPopover: typeof import('./src/components/layout/LoginPopover.vue')['default']
    MultipleSelect: typeof import('./src/components/form/MultipleSelect.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFormField: typeof import('./src/components/form/SelectFormField.vue')['default']
    TextareaField: typeof import('./src/components/form/TextareaField.vue')['default']
    Wardrobe: typeof import('./src/components/clothing/Wardrobe.vue')['default']
  }
}
